config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :reports, only: [:create] 
  root 'posts#index'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  validates :title, presence: true, length: { maximum: 20 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  has_many :reports, as: :reportable

  paginates_per 5



  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  default_scope { order('created_at DESC') }

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  acts_as_commentable

  paginates_per 5

  attr_accessor :category_string

  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true

  before_validation :set_category

  protected

  def set_category
    if self.category_string.nil?
      self.category = Category.find_or_create_by(title: "Misc")
    else
      errors.add(:category_string, "Invalid category") unless (self.category = Category.find_or_create_by(title: self.category_string)).valid?
    end
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :reportable, polymorphic: true
  # validates :reason, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  has_many :reports

  ratyrate_rater
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:comment][:post_id])
    @comment = Comment.build_from(@post, current_user.id, params[:comment][:body])
    @comments = @post.root_comments.page(params[:comment][:page])
    if @comment.save
      flash[:notice] = "Commented"
    else
      flash[:alert] = "something went wrong"
    end
    @comment.move_to_child_of(Comment.find(params[:comment][:commentable_id])) if params[:comment][:commentable_type] == "Comment"
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end


  private

  def comments_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type, :post_id, :page)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @posts = Post.page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    @post.user = current_user # Currently there is only one author
    if @post.save
      redirect_to @post, notice: "Post successfully created"
    else
      flash.now[:alert] = "Somethng went wrong"
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(posts_params)
      redirect_to @post, notice: "Post successfully updated"
    else
      flash.now[:alert] = "Somethng went wrong"
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete
    redirect_to post_index_path, notice: "Post has been deleted"
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.root_comments.page(params[:page])
  end

  private

  def posts_params
    params.require(:post).permit(:title, :category_string, :body)
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  def create
    @report = Report.new(report_params)
    @report.user = current_user
    if @report.save
      flash[:notice] = "Reported"
    else
      flash[:alert] = "something went wrong"
    end
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end


  private

   def report_params
     params.require(:report).permit(:reason, :reportable_id, :reportable_type)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(no_intra_emphasis: true, hard_wrap: true, autolink: true)
    markdown = Redcarpet::Markdown.new(renderer, autolink: true, tables: true, safe_links_only: true, fenced_code_blocks: true)
    markdown.render(text.to_s).html_safe
  end


end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-section clearfix">
  <div class="comment <%= "reported" if comment.reports.count > 5 %>">
    <% if comment.user.nil? %>
      <p>[deleted]</p>
    <% else %>
      <p><%= markdown(comment.body) =%></p>
      <small><%= time_ago_in_words(comment.created_at) %> ago</small>
      <% unless current_user.nil? %>
        <small class="comment-reply"><a href="#">Reply</a></small>
        <small class="report-user"><%= link_to "report", reports_path(report: {reportable_id: comment.id, reportable_type: "Comment"}), method: :post unless comment.reports.where(user: current_user).any? %></a></small>
      <% end %>
    <% end %>
    <small class="comment-user">By: <%= "Dummy user" %></small><!-- comment.user.name -->
  </div>
  <div class="comment2">
    <%= render partial: "comments/comment", collection: comment.children, locals: { post_id: post_id } if comment.has_children? %>
  </div>
  <div class="comment-form">
    <%= simple_form_for(Comment.new, remote: true) do |f| %>
      <%= f.input :body, label: "Reply", input_html: {class: "comment-box"} %>
      <%= f.input_field :commentable_id, as: :hidden, value: comment.id %>
      <%= f.input_field :commentable_type, as: :hidden, value: "Comment" %>
      <%= f.input_field :post_id, as: :hidden, value: post_id %>
      <%= f.input_field :page, as: :hidden, value: params[:page] %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$("#comments").html('<%= j render partial: 'comments/comment', collection: @comments, locals: { post_id: @post.id } %>');

$(".comment-box").val('');
$(".comment-form").css('display', 'none');
$(".comment-reply").on ("click", function(event) {
  event.preventDefault();
  $(this).parent().next().next().toggle(function() {
    $(this).parent().next().next().css("display", "block");
  }, function() {
    $(this).parent().next().next().css("display", "none");
  });
});
$(".report-form").css('display', 'none');
$(".report-user").on ("click", function(event) {
  event.preventDefault();
  $(this).parent().next().next().next().toggle(function() {
    $(this).parent().next().next().next().css("display", "block");
  }, function() {
    $(this).parent().next().next().next().css("display", "none");
  });
});

app/views/layouts/_flash.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_topbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">RacketLogger</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts/new">New Post</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RLReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<% if controller.controller_name == 'posts' %>
  <body data-no-turbolink>
<% else %>
  <body >
<% end %>
<%= render 'layouts/topbar' %>
<%= render 'layouts/flash' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
  <%= simple_form_for @post,  html: { class: 'form-horizontal' } do |f| %>
    <%= f.input :title %>
    <%= f.input :category_string, collection: %w(Racquet String) ,required: true %>
    <%= f.input :body %>
    <%= f.button :submit %>
  <% end %>
  

app/views/posts/edit.html.erb
<h1 class="show-post-title">Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<header>
  <h1 class="main-h1-title">All Posts</h1>
</header>
<% @posts.each do |post| %>
<div class="panel panel-default">
  <article>
    <h2 class="post-title"><%= link_to post.title, post_path(post) %></h2>
    <div class="clearfix">
      <small class="post-time"><%= post.created_at.to_date %></small>
      <p class="author">Author</p>
    </div>
    <div class="panel-body">
      <%= post.body %>
    </div>
  </div>
</article>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-offset-4 col-md-4"><%= paginate @posts %></div>
  </row>
</div>

app/views/posts/new.html.erb
<h1 class="show-post-title">New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<article>
  <h2 class="show-post-title"><%= @post.title %></h1>
  <small class="post-time"><%= @post.created_at.to_date %></small>
  <p class="author">Author</p>
  <div class="main-content" role="main">
    <%= @post.body %>
  </div>
  <% if current_user.nil? %>
    <div>Login to Rate the Article</div>
  <% else %>
    <%= rating_for @post, "useful", disable_after_rate: true, imdb_avg: true %>
  <% end %>
</article>
<div class="panel panel-default">
  <div class="panel-heading">Comments</div>
  <div class="panel-body">
    <div id="comments">
      <%= render partial: "comments/comment", collection: @comments, locals: { post_id: @post.id } %>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4" id="paginator"><%= paginate @comments %></div>
    </div>
    <% if current_user.nil? %>
      <div>Login to Post comment</div>
    <% else %>
      <div>
        <%= simple_form_for(Comment.new, remote: true) do |f| %>
          <%= f.input :body, label: "Reply", input_html: {class: "comment-box"} %>
          <%= f.input_field :commentable_id, as: :hidden, value: @post.id %>
          <%= f.input_field :commentable_type, as: :hidden, value: "Post" %>
          <%= f.input_field :post_id, as: :hidden, value: @post.id %>
          <%= f.input_field :page, as: :hidden, value: params[:page] %>
          <%= f.button :submit %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<script>
  $(".comment-form").css('display', 'none');
  $(".comment-reply").on ("click", function(event) {
    event.preventDefault();
    $(this).parent().next().next().toggle(function() {
      $(this).parent().next().next().css("display", "block");
    }, function() {
      $(this).parent().next().next().css("display", "none");
    });
  });
  $(".report-form").css('display', 'none');
  $(".report-user").on ("click", function(event) {
    event.preventDefault();
    $(this).parent().next().next().next().toggle(function() {
      $(this).parent().next().next().next().css("display", "block");
    }, function() {
      $(this).parent().next().next().next().css("display", "none");
    });
  });
</script>